apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: cilium-agent-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-agent-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cilium-agent-proxy
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - image: ghcr.io/cybozu/envoy
          name: envoy
          command: ["envoy", "-c", "/etc/envoy/envoy-config.yaml"]
          args: []
          volumeMounts:
            - name: cilium-socket
              mountPath: /var/run/cilium
            - name: envoy-config
              mountPath: /etc/envoy
          securityContext:
            capabilities:
              drop:
                - ALL
      volumes:
        - name: cilium-socket
          hostPath:
            path: /var/run/cilium
        - name: envoy-config
          configMap:
            name: cilium-agent-proxy
