apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-agent-proxy.yaml
  - ubuntu.yaml
configMapGenerator:
  - namespace: kube-system
    name: cilium-agent-proxy
    files:
      - envoy-config.yaml
images:
  - name: ghcr.io/cybozu/envoy
    newTag: 1.28.1.1
