[book]
language = "en"
multilingual = false
src = "."
title = "Template Documentation"

[output.html]
git-repository-url = "https://github.com/cybozu-go/cilium-policy-viewer"
edit-url-template = "https://github.com/cybozu-go/cilium-policy-viewer/edit/main/docs/{path}"
site-url = "/cilium-policy-viewer/"
